### ISSUE TITLE
Week 8 : Experiments Links !!

### ISSUE THREAD

**Issue by rishi11** [chengchen886/CS5610-charlie#11]
In insert operation experiment you copied my experiments and gave link to my experiments !!!

This is NOT acceptable.

Please perform YOUR experiments during the course !!

**Comment by chengchen886** [comment]
Hi Rishi,

That's what I want to ask, I have enter some problem for mongoDB environment, I want to come at TA hours to ask about this.

Thank you,
Cheng

----- Original Message -----

**Comment by chengchen886** [comment]
Hi Rishi,

I have delete the insert operation experiment, the reason is that I feel your experiment is really interesting, and I try to setup openshift environment, but I encountered some problem that I still can not figure it out yet. Hope I can ask you at TA hours.
Sorry about that.

Thanks,
Charlie

----- Original Message -----
